"""Write and load committed fixtures.

Small tables are written as readable `.sql` INSERTs so a reviewer can open them.
`usage_daily` is inherently machine data (tens of thousands of rows), so it is
written as a zstd-compressed CSV and loaded via COPY — small in the repo, fast to
load, and still fully deterministic.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
from pathlib import Path

import zstandard as zstd

REPO = Path(__file__).resolve().parents[1]
FIX = REPO / "db" / "fixtures"
TRUTH = REPO / "eval" / "truth" / "ground_truth.csv"


def _sql_literal(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def _insert_file(path: Path, table: str, columns: list[str], rows: list[dict]) -> None:
    lines = [
        f"-- {table}: {len(rows)} rows. Generated by datagen; do not edit by hand.",
        f"TRUNCATE {table} CASCADE;",
    ]
    for r in rows:
        vals = ", ".join(_sql_literal(r.get(c)) for c in columns)
        lines.append(f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({vals});")
    path.write_text("\n".join(lines) + "\n")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# Column order per table (must match schema.sql).
COLS = {
    "features": ["id", "name", "description", "area", "launched_at",
                 "maintenance_cost_band", "annual_maintenance_usd",
                 "replacement_feature_id"],
    "accounts": ["id", "name", "arr_band", "arr_usd", "segment", "industry",
                 "signed_at"],
    "feature_dependencies": ["from_feature_id", "to_feature_id", "kind"],
    "contracts": ["id", "account_id", "title", "effective_from", "expires_at"],
    "contract_clauses": ["id", "contract_id", "section", "text"],
    "deal_notes": ["id", "account_id", "outcome", "closed_at", "body"],
    "support_tickets": ["id", "account_id", "feature_id_guess", "created_at",
                        "subject", "body", "resolution"],
}


def write_fixtures(data: dict, seed: int, dataset_version: str) -> None:
    FIX.mkdir(parents=True, exist_ok=True)

    _insert_file(FIX / "010_features.sql", "features", COLS["features"], data["features"])
    _insert_file(FIX / "020_accounts.sql", "accounts", COLS["accounts"], data["accounts"])
    _insert_file(FIX / "030_dependencies.sql", "feature_dependencies",
                 COLS["feature_dependencies"], data["dependencies"])
    _insert_file(FIX / "040_contracts.sql", "contracts", COLS["contracts"], data["contracts"])
    _insert_file(FIX / "050_contract_clauses.sql", "contract_clauses",
                 COLS["contract_clauses"], data["clauses"])
    _insert_file(FIX / "060_deal_notes.sql", "deal_notes", COLS["deal_notes"], data["deals"])
    _insert_file(FIX / "070_support_tickets.sql", "support_tickets",
                 COLS["support_tickets"], data["tickets"])

    # usage_daily -> compressed CSV
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["feature_id", "account_id", "day", "actor_type", "active_users", "events"])
    for u in data["usage"]:
        w.writerow([u.feature_id, u.account_id, u.day.isoformat(),
                    u.actor_type, u.active_users, u.events])
    raw = buf.getvalue().encode()
    comp = zstd.ZstdCompressor(level=19).compress(raw)
    (FIX / "080_usage_daily.csv.zst").write_bytes(comp)

    manifest = {
        "seed": seed,
        "dataset_version": dataset_version,
        "truth_sha256": _sha256(TRUTH),
        "row_counts": {k: len(v) for k, v in data.items() if k != "clause_map"},
        "files": {},
    }
    for p in sorted(FIX.glob("*")):
        if p.name == "MANIFEST.json":
            continue
        manifest["files"][p.name] = _sha256(p)
    (FIX / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def load_fixtures(conn) -> dict:
    """Load all fixtures into an open psycopg connection. Returns row counts."""
    sql_files = sorted(FIX.glob("0*.sql"))
    with conn.cursor() as cur:
        for p in sql_files:
            cur.execute(p.read_text())
        # usage_daily via COPY
        comp = (FIX / "080_usage_daily.csv.zst").read_bytes()
        raw = zstd.ZstdDecompressor().decompress(comp).decode()
        reader = csv.reader(io.StringIO(raw))
        next(reader)  # header
        cur.execute("TRUNCATE usage_daily CASCADE;")
        with cur.copy(
            "COPY usage_daily (feature_id, account_id, day, actor_type, "
            "active_users, events) FROM STDIN"
        ) as cp:
            for row in reader:
                cp.write_row(row)
    conn.commit()

    counts = {}
    with conn.cursor() as cur:
        for t in ["features", "accounts", "feature_dependencies", "contracts",
                  "contract_clauses", "deal_notes", "support_tickets", "usage_daily"]:
            cur.execute(f"SELECT count(*) FROM {t}")
            counts[t] = cur.fetchone()[0]
    return counts
