-- contracts: 12 rows. Generated by datagen; do not edit by hand.
TRUNCATE contracts CASCADE;
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c01', 'a01', 'Master Services Agreement — a01', '2023-11-18', '2026-11-17');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c02', 'a02', 'Master Services Agreement — a02', '2023-01-21', '2026-01-20');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c03', 'a03', 'Master Services Agreement — a03', '2023-04-16', '2026-04-15');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c04', 'a04', 'Master Services Agreement — a04', '2023-07-01', '2026-06-30');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c05', 'a05', 'Master Services Agreement — a05', '2023-12-29', '2026-12-28');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c06', 'a06', 'Master Services Agreement — a06', '2023-08-11', '2026-08-10');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c07', 'a07', 'Master Services Agreement — a07', '2024-01-24', '2027-01-23');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c08', 'a08', 'Master Services Agreement — a08', '2023-09-05', '2026-09-04');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c09', 'a09', 'Master Services Agreement — a09', '2023-05-18', '2026-05-17');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c10', 'a10', 'Master Services Agreement — a10', '2023-05-21', '2026-05-20');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c11', 'a11', 'Master Services Agreement — a11', '2023-02-20', '2026-02-19');
INSERT INTO contracts (id, account_id, title, effective_from, expires_at) VALUES ('c12', 'a12', 'Master Services Agreement — a12', '2023-12-31', '2026-12-30');
